In [ ]:
import pandas as pd
from vertexai.evaluation import EvalTask
import vertexai.evaluation.metrics.pointwise_metric as pointwise_metric
# Pointwise 검사를 위한 데이터셋 준비
# Pointwise는 단일 모델의 결과에 대한 평가입니다.
data = [
    ["This account is not protected with a two-factor authentication.", 
     "2차 인증이 되지 않은 계정입니다.",
     "이중 인증으로 보호되지 않은 계정입니다."],
    ["Even the longest journey begins with a single step.",
    "천 리 길도 한 걸음부터.",
    "가장 먼 여정도 한 걸음에서 시작됩니다."],
    ["Even the longest journey begins with a single step.",
    "Лиха беда начало.",
    "Даже самая длинная дорога продолжается с одного шага."]
]
sample_df = pd.DataFrame(data, columns=['source', 'reference', 'response'])
sample_df

,source,reference,response
0,This account is not protected with a two-facto...,2차 인증이 되지 않은 계정입니다.,이중 인증으로 보호되지 않은 계정입니다.
1,Even the longest journey begins with a single ...,천 리 길도 한 걸음부터.,가장 먼 여정도 한 걸음에서 시작됩니다.
2,Even the longest journey begins with a single ...,Лиха беда начало.,Даже самая длинная дорога продолжается с одног...

In [ ]:
import google.auth
import vertexai
_, PROJECT_ID = google.auth.default()
LOCATION = "us-central1"
vertexai.init(project=PROJECT_ID, location=LOCATION)
eval_task = EvalTask(dataset=sample_df[['source', 'reference']].rename(columns={'reference': 'response'}),
                    metrics=[pointwise_metric.MetricX(version="METRICX_24_SRC")], #"METRICX_24_SRC_REF", "METRICX_24_SRC", or "METRICX_24_REF".
                    experiment="pointwise-eval")
result_pointwise = eval_task.evaluate()
result_pointwise.metrics_table

#metricx, lower is better (0-25)
#From the paper, https://aclanthology.org/2024.wmt-1.35/
# 0 ~ 1 is good
# above 5 means undertranslation

Associating projects/1045259343465/locations/us-central1/metadataStores/default/contexts/pointwise-eval-21465365-95d5-4105-a750-4ac0657494f1 to Experiment: pointwise-eval

Computing metrics with a total of 3 Vertex Gen AI Evaluation Service API requests.

100%|██████████| 3/3 [00:05<00:00,  1.71s/it]

All 3 metric requests are successfully computed.
Evaluation Took:5.151485299982596 seconds

,source,response,metricx/score
0,This account is not protected with a two-facto...,2차 인증이 되지 않은 계정입니다.,0.950510
1,Even the longest journey begins with a single ...,천 리 길도 한 걸음부터.,0.652064
2,Even the longest journey begins with a single ...,Лиха беда начало.,3.064888

In [6]:
eval_task = EvalTask(dataset=sample_df[['source', 'response']],
                    metrics=[pointwise_metric.MetricX(version="METRICX_24_SRC")],
                    experiment="pointwise-eval")
result_pointwise = eval_task.evaluate()
result_pointwise.metrics_table

#metricx, lower is better (0-25)
#From the paper, https://aclanthology.org/2024.wmt-1.35/
# 0 ~ 1 is good
# above 5 means undertranslation

Associating projects/1045259343465/locations/us-central1/metadataStores/default/contexts/pointwise-eval-358a14fd-074c-4b72-bd96-5018db3c0bdd to Experiment: pointwise-eval

Computing metrics with a total of 3 Vertex Gen AI Evaluation Service API requests.

100%|██████████| 3/3 [00:04<00:00,  1.64s/it]

All 3 metric requests are successfully computed.
Evaluation Took:4.931300800002646 seconds

,source,response,metricx/score
0,This account is not protected with a two-facto...,이중 인증으로 보호되지 않은 계정입니다.,0.640757
1,Even the longest journey begins with a single ...,가장 먼 여정도 한 걸음에서 시작됩니다.,0.894905
2,Even the longest journey begins with a single ...,Даже самая длинная дорога продолжается с одног...,4.401481

In [7]:
eval_task = EvalTask(dataset=sample_df[['source', 'reference', 'response']],
                    metrics=[pointwise_metric.Comet(version="COMET_22_SRC_REF")],
                    experiment="pointwise-eval")
result_pointwise = eval_task.evaluate()
result_pointwise.metrics_table

#comet, higher is better (0-1)
#From the paper, https://aclanthology.org/2022.wmt-1.52

Associating projects/1045259343465/locations/us-central1/metadataStores/default/contexts/pointwise-eval-d775698f-80fd-4b52-9e7e-ab7b7de9a39c to Experiment: pointwise-eval

Computing metrics with a total of 3 Vertex Gen AI Evaluation Service API requests.

100%|██████████| 3/3 [00:03<00:00,  1.03s/it]

All 3 metric requests are successfully computed.
Evaluation Took:3.3337916000164114 seconds

,source,reference,response,comet/score
0,This account is not protected with a two-facto...,2차 인증이 되지 않은 계정입니다.,이중 인증으로 보호되지 않은 계정입니다.,0.915181
1,Even the longest journey begins with a single ...,천 리 길도 한 걸음부터.,가장 먼 여정도 한 걸음에서 시작됩니다.,0.925086
2,Even the longest journey begins with a single ...,Лиха беда начало.,Даже самая длинная дорога продолжается с одног...,0.568027